/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lab1;

/**
 *
 * @author hariom
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelusername = new javax.swing.JLabel();
        labelpsw = new javax.swing.JLabel();
        jusername = new javax.swing.JTextField();
        jPassword = new javax.swing.JPasswordField();
        Buttomlogin = new javax.swing.JButton();
        buttomclear = new javax.swing.JButton();
        buttomexit = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelusername.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        labelusername.setForeground(new java.awt.Color(255, 51, 51));
        labelusername.setText("Username:");
        getContentPane().add(labelusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 110, -1, -1));

        labelpsw.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        labelpsw.setForeground(new java.awt.Color(255, 51, 51));
        labelpsw.setText("Password:");
        getContentPane().add(labelpsw, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 160, -1, -1));

        jusername.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        getContentPane().add(jusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 110, 194, -1));

        jPassword.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        getContentPane().add(jPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 160, 194, -1));

        Buttomlogin.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Buttomlogin.setText("Login");
        getContentPane().add(Buttomlogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 230, -1, -1));

        buttomclear.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        buttomclear.setText("Clear");
        getContentPane().add(buttomclear, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 230, -1, -1));

        buttomexit.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        buttomexit.setText("Exit");
        getContentPane().add(buttomexit, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 230, -1, -1));

        jLabel4.setFont(new java.awt.Font("DejaVu Serif", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Login ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 30, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lab1/bg.3.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, -30, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Buttomlogin;
    private javax.swing.JButton buttomclear;
    private javax.swing.JButton buttomexit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField jPassword;
    private javax.swing.JTextField jusername;
    private javax.swing.JLabel labelpsw;
    private javax.swing.JLabel labelusername;
    // End of variables declaration//GEN-END:variables
}
